name: pytorch3.6
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.6=h14c3975_1002
  - cairo=1.14.12=he56eebe_3
  - dbus=1.13.0=h4e0c4b3_1000
  - expat=2.2.5=hf484d3e_1002
  - ffmpeg=4.0.2=ha6a6e2b_0
  - fontconfig=2.13.0=hd36ec8e_5
  - freetype=2.8.1=hfa320df_1
  - gettext=0.19.8.1=h9745a5d_1001
  - giflib=5.1.7=h516909a_1
  - glib=2.55.0=h464dc38_2
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.5.19=h2a4e5f8_1
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.12.5=h3865690_1000
  - gstreamer=1.12.5=h61a6719_0
  - harfbuzz=1.8.5=h2bb21d5_0
  - icu=58.2=hf484d3e_1000
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9c=h14c3975_1001
  - lame=3.100=h14c3975_1001
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libiconv=1.15=h14c3975_1004
  - libpng=1.6.36=h84994c4_1000
  - libprotobuf=3.5.2=hd28b015_1
  - libtiff=4.0.10=h648cc4a_1001
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=0.5.2=7
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.8=h143f9aa_1005
  - mkl_fft=1.0.10=py36_0
  - mkl_random=1.0.2=py36_0
  - nettle=3.3=0
  - openblas=0.2.20=8
  - openh264=1.7.0=0
  - pillow=5.2.0=py36h2dc6135_1
  - pixman=0.34.0=h14c3975_1003
  - pthread-stubs=0.4=h14c3975_1001
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.9=h516909a_1004
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.7=h14c3975_1000
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py36_0
  - cffi=1.12.2=py36h2e261b9_1
  - cudatoolkit=9.0=h13b8566_0
  - freeglut=3.0.0=hf484d3e_5
  - hdf5=1.10.2=hba1933b_1
  - intel-openmp=2019.1=144
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libglu=9.0.0=hf484d3e_1
  - libopenblas=0.2.20=h9ac9557_7
  - libopencv=3.4.1=h1a3b859_1
  - libopus=1.3=h7b6447c_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libvpx=1.7.0=h439df22_0
  - mkl=2019.1=144
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.16.2=py36h7e9f1db_0
  - numpy-base=1.16.2=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - opencv=3.4.1=py36h6fd60c2_2
  - openssl=1.1.1b=h7b6447c_1
  - pcre=8.43=he6710b0_0
  - pip=19.0.3=py36_0
  - py-opencv=3.4.1=py36h0676e08_1
  - pycparser=2.19=py36_0
  - python=3.6.8=h0371630_0
  - qt=4.8.7=2
  - readline=7.0=h7b6447c_5
  - scipy=1.2.1=py36h7c811a0_0
  - setuptools=40.8.0=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.27.2=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pytorch=1.0.1=py3.6_cuda9.0.176_cudnn7.4.2_2
  - torchvision=0.2.2=py_3
  - pip:
    - protobuf==3.7.1
    - tensorboardx==1.6
    - torch==1.0.1.post2
prefix: /home/paperspace/anaconda3/envs/pytorch3.6

